server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**

        - id: issue-service
          uri: lb://issue-service
          predicates:
            - Path=/api/issues/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
