spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
        - id: issue-service
          uri: lb://issue-service
          predicates:
            - Path=/issue/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: attachment-service
          uri: lb://attachment-service
          predicates:
            - Path=/attachment/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/audit/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/report/**
