spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/Config_Board
  cloud:
    config:
      override-system-properties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      root: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  logging:
    level:
      root: INFO
