spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attachmentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9091/realms/Config_Board/protocol/openid-connect/certs
