server:
  port: 9100

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
